# Generated by Django 4.2.13 on 2026-05-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_id', models.CharField(max_length=50)),
                ('sensor', models.CharField(max_length=50)),
                ('similarity_score', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('first_deviation_index', models.IntegerField(blank=True, null=True)),
                ('first_deviation_timestamp', models.CharField(blank=True, max_length=50, null=True)),
                ('deviation_count', models.IntegerField(default=0)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='IdealSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=50)),
                ('values_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TankReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_id', models.CharField(max_length=50)),
                ('sensor', models.CharField(max_length=50)),
                ('values_json', models.TextField()),
                ('timestamps_json', models.TextField()),
                ('fault_type', models.CharField(default='none', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
